# -*- coding: utf-8 -*-
"""TAREA 1_MG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJ-gEbE8g7HIxXE0IzAGqriruarpAsGr

# Título del Proyecto: Proceso de admisión universitaria de los estudiantes de la Generación Z
---
###Nombre del maestrante: Mónica Gallegos V.
###Módulo: Big Data, Analytics & Data Scientist.
###Docente: MSc. Carlos Carrillo.
###Tema del análisis: Admisión de estudiantes_generaciónZ
###Fecha: Julio 2026
---

##Descripción:
El conjunto de datos de predicción de admisión universitaria para la Generación Z es un conjunto de datos sintéticos a gran escala diseñado para modelar el proceso de admisión universitaria de los estudiantes de la Generación Z. A diferencia de los conjuntos de datos de admisión tradicionales, que se centran principalmente en el rendimiento académico, este conjunto incorpora una gama más amplia de factores que reflejan el panorama educativo en constante evolución, la participación digital, las actividades extracurriculares, la experiencia de liderazgo y el contexto socioeconómico de los estudiantes actuales.

El conjunto de datos contiene 1.000.000 de registros de estudiantes y está destinado a la investigación, el aprendizaje automático, las competiciones de ciencia de datos, el análisis predictivo, los estudios educativos y los desafíos de ingeniería de características.

###Importación de librerías
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

"""### Carga y lectura del dataset"""

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/genz_college_admission_prediction.csv")

"""###Limpieza y preparación
Revisión de nulos, duplicados, formatos, tipos de datos, fechas, outliers y transformaciones necesarias.
"""

# 1. Se revisa los primeros registros del dataset.
df.head()

#2. Visualiza las últimas filas de un DataSet
df.tail()

#3.Se obtiene un resumen detallado de la estructura del DataSet
df.info()

#4. Se genera un resumen rápido de la tendencia central, dispersión y forma de los datos
df.describe()

#5. Se identifican valores faltantes o nulos en el data set
df.isnull()

#6. Se cuenta la cantidad de valores nulos o faltantes en el dataset
df.isnull().sum()

#7. Cuenta el numero de filas duplicadas
df.duplicated().sum()

#8. Se identifica el tipo de datos almacenados en cada una de las columnas de tu Dataset.
df.dtypes

#9. Identificar número de filas y columnas del dataset
df.shape

#10. Cuenta el número de valores únicos (distintos) para cada columna en un DataFrame.
df.nunique()

#11. lista con las etiquetas que identifican cada columna del dataset
df.columns

"""##EDA - Análisis de datos exploratorio

---


### Objetivo

El presente análisis tiene como finalidad explorar, visualizar e identificar patrones en los datos relacionados con la admisión universitaria de estudiantes. Se aplican técnicas de estadística descriptiva, visualización de datos y análisis de correlación para comprender los factores asociados al estado de admisión.

### Desarrollo de la programación
A partir de las visualizaciones generadas se busca:
1. Comprender la estructura del dataset.
2. Identificar patrones de admisión.
3. Detectar relaciones entre variables académicas y personales.
4. Seleccionar variables relevantes para Machine Learning.
5. Generar conocimiento útil para la toma de decisiones en procesos de admisión universitaria.

#### Librerías consideradas

Las principales librerías utilizadas para el análisis:

- **Pandas:** Manipulación y análisis de datos.

- **NumPy:** Operaciones numéricas.

- **Matplotlib:** Visualización gráfica.

- **Seaborn:** Visualización estadística avanzada.
"""

# DATA SET ADMISION DE ESTUDIANTES- FLUJO COMPLETO DE VISUALIZACION
# Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# CARGA DE DATOS DEL DATASET
# Se verifica la dimensión del conjunto de datos y se muestran los nombres
# de las variables disponibles.
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns)

# AJUSTES DE ESTILO Y CONFIGURACIÓN
# Se define un estilo visual uniforme para todos los gráficos generados durante
# el análisis.
plt.style.use('seaborn-v0_8-whitegrid')
sns.set_theme(style="whitegrid")

# DESCRIPCION DEL DATASET
# Se inspecciona la estructura de los datos y se identifican posibles problemas
# de calidad.

print("\nInformación del Dataset")
print(df.info())

print("\nValores faltantes")
print(df.isnull().sum())

print("\nResumen estadístico")
print(df.describe())

# Aspectos que se analiza:
#- Tipo de dato de cada variable.
#- Valores faltantes.
#- Medidas estadísticas básicas:
#- Media
#- Desviación estándar
#- Valores mínimos y máximos
#- Cuartiles


# Distribución de la variable objetivo "estado de admisión"
# La variable *admission_status* representa el resultado del proceso de admisión.
# Este gráfico permite:
# Identificar la proporción de estudiantes admitidos y no admitidos.
# Detectar posibles problemas de desbalance de clases.
# Evaluar la distribución de la variable objetivo antes del modelado.

plt.figure(figsize=(8,5))
sns.countplot(
    x='admission_status',
    data=df,
    palette='Set2'
)

plt.title("Admission Status Distribution",
          fontsize=16,
          fontweight='bold')

plt.xlabel("Estado de Adminión")
plt.ylabel("Cuenta")

plt.show()

# Se analiza la composición demográfica de los estudiantes según su género.
# Se busca obtener:
# Representatividad de cada género.
# Posibles sesgos en la población estudiada.

plt.figure(figsize=(7,5))

sns.countplot(
    x='gender',
    data=df,
    palette='pastel'
)

plt.title("Distribución por Género")
plt.show()

# Se visualiza el número de estudiantes provenientes de cada estado.
# Este análisis ayuda a:
# Identificar estados con mayor participación.
# Detectar patrones geográficos relevantes.

plt.figure(figsize=(14,6))
state_counts = df['state'].value_counts()
sns.barplot(
    x=state_counts.index,
    y=state_counts.values,
    palette='viridis'
)
plt.title("Estudiantes por Estado")
plt.xticks(rotation=45)
plt.show()

# Distribucion de los ingresos familiares
# Se analiza el comportamiento de la variable **family_income**.
# Permite observar:
# Concentración de ingresos.
# Asimetría de la distribución.
# Posibles valores atípicos.

plt.figure(figsize=(10,5))
sns.histplot(
    df['family_income'],
    bins=30,
    kde=True,
    color='green'
)
plt.title("Distribución de ingresos familiares")
plt.show()

# Distribucion de promedio de calificaciones de secundaria
# El GPA suele ser uno de los principales predictores del éxito académico y de la admisión universitaria.

plt.figure(figsize=(10,5))

sns.histplot(
    df['high_school_gpa'],
    bins=25,
    kde=True,
    color='orange'
)

plt.title("Promedio de calificaciones de colegio")
plt.show()

# Análisis estadistico que muestra cómo se agrupan los resultados de todos los
# estudiantes que rinden este examen de admisión universitaria
# Permite identificar:
# Niveles de desempeño académico.
# Variabilidad de los puntajes.

plt.figure(figsize=(10,5))
sns.histplot(
    df['sat_score'],
    bins=25,
    kde=True,
    color='royalblue'
)
plt.title("Distribución de puntaje SAT")
plt.show()

# Distribución de puntaje del examen

plt.figure(figsize=(10,5))
sns.histplot(
    df['act_score'],
    bins=20,
    kde=True,
    color='crimson'
)
plt.title("ACT Distribución de puntaje")
plt.show()

# Distribución de la tasa de asistencia, que suele ser un indicador de
# compromiso académico.
# Permite identificar patrones de asistencia y posibles relaciones con la admisión

plt.figure(figsize=(10,5))

sns.histplot(
    df['attendance_rate'],
    bins=20,
    kde=True,
    color='purple'
)

plt.title("Tasa de asistencia")
plt.show()

# Promedio versus el estado de adminión
# Se compara el rendimiento académico entre estudiantes admitidos y no admitidos

plt.figure(figsize=(8,5))

sns.boxplot(
    x='admission_status',
    y='high_school_gpa',
    data=df,
    palette='coolwarm'
)

plt.title("Promedio versus estado de adminsión")
plt.show()

# Puntuación SAT vs Estado de Adminisión
# Se evalua la influencia de los puntajes SAT en el proceso de admisión.

plt.figure(figsize=(8,5))

sns.boxplot(
    x='admission_status',
    y='sat_score',
    data=df,
    palette='Set3'
)

plt.title("Puntuación SAT vs Estado de adminisión")
plt.show()


# Estado de asistencia frente a tasa de admisión

plt.figure(figsize=(8,5))

sns.boxplot(
    x='admission_status',
    y='attendance_rate',
    data=df,
    palette='Spectral'
)

plt.title("Estado de Asistencia vs Adminisión")
plt.show()

# Promedio de calificaciones vs puntuación SAT
# Permite identificar:
# Relación entre desempeño académico y pruebas estandarizadas.
# Separación visual entre estudiantes admitidos y no admitidos.

plt.figure(figsize=(10,6))

sns.scatterplot(
    x='high_school_gpa',
    y='sat_score',
    hue='admission_status',
    palette='Dark2',
    data=df
)

plt.title("Promedio vs puntuación SAT")
plt.show()

# Puntuación del Ensayo vs Puntuación de la entrevista
# Analiza la influencia de variables cualitativas en la decisión de admisión.

plt.figure(figsize=(10,6))

sns.scatterplot(
    x='essay_score',
    y='interview_score',
    hue='admission_status',
    palette='tab10',
    data=df
)

plt.title("Puntuación del Ensayo vs Puntuación de la entrevista")
plt.show()

# Puestos de liderazgo
# Evalúa el nivel de participación de los estudiantes en actividades de liderazgo.

plt.figure(figsize=(10,5))

sns.histplot(
    df['leadership_positions'],
    bins=15,
    color='darkorange'
)

plt.title("Distribución de puestos de liderazgo")
plt.show()

# Proyectos de Programación
# Se identifica habilidades técnicas y experiencia práctica.

plt.figure(figsize=(10,5))

sns.histplot(
    df['coding_projects'],
    bins=15,
    color='teal'
)

plt.title("Distribución de proyectos de programación")
plt.show()

# Distribución de Certificados Online
# Mide el nivel de formación complementaria de los estudiantes.

plt.figure(figsize=(10,5))

sns.histplot(
    df['online_certifications'],
    bins=15,
    color='brown'
)

plt.title("Certificados Online")
plt.show()


# Matriz de Correlación.
# CORRELATION HEATMAP: visualización gráfica de una matriz de correlación,
# que muestra la fuerza, la dirección y la significación estadística de las
# relaciones lineales entre múltiples variables en un conjunto de datos y
# seleccionar variables relevantes para Machine Learning.

numeric_cols = df.select_dtypes(include=np.number)

plt.figure(figsize=(15,10))

sns.heatmap(
    numeric_cols.corr(),
    annot=True,
    cmap='RdYlBu',
    fmt='.2f'
)

plt.title("Correlation Heatmap")
plt.show()


# Pairplot de Variables Relevantes: visualización de datos que muestra todas las relaciones posibles
# entre las variables numéricas de un conjunto de datos en una sola cuadrícula

important_cols = [
    'high_school_gpa',
    'sat_score',
    'attendance_rate',
    'essay_score',
    'interview_score',
    'admission_status'
]

sns.pairplot(
    df[important_cols],
    hue='admission_status',
    palette='husl'
)

plt.show()

# Estilo visual de la importancia de las características
# conjunto de datos tienen mayor influencia en las predicciones

numeric_cols = [
    'family_income',
    'high_school_gpa',
    'sat_score',
    'act_score',
    'attendance_rate',
    'ap_courses',
    'extracurricular_count',
    'volunteer_hours',
    'leadership_positions',
    'coding_projects',
    'online_certifications',
    'essay_score',
    'recommendation_score',
    'interview_score'
]

correlations = []

for col in numeric_cols:

    corr = df[col].corr(
        pd.factorize(df['admission_status'])[0]
    )

    correlations.append(abs(corr))


# Se calcula la correlación absoluta de cada variable numérica con la variable objetivo.
# Este gráfico permite identificar cuáles variables presentan mayor influencia en la admisión universitaria.
# Las variables con mayor correlación pueden considerarse candidatas prioritarias para la construcción de modelos predictivos.

feature_df = pd.DataFrame({
    'Feature': numeric_cols,
    'Correlation': correlations
})

feature_df = feature_df.sort_values(
    by='Correlation',
    ascending=False
)

plt.figure(figsize=(12,7))

sns.barplot(
    x='Correlation',
    y='Feature',
    data=feature_df,
    palette='rocket'
)

plt.title("Futuro impacto sobre el estado de adminisión")
plt.show()

# ============================================================
# FIN
# ============================================================

print("\nEDA Completado satisfactoriamente")
print("20Visualizaciones generadas")

"""##Resultados y conclusiones

##Hallazgos principales
El conjunto de datos es grande y de buena calidad.
No existen valores faltantes.
La mayoría de estudiantes son admitidos (88%).
Las variables académicas son potencialmente los factores más influyentes.
Los indicadores extracurriculares complementan el perfil del estudiante.
##Desempeño esperado del modelo
Un Random Forest debería alcanzar un desempeño elevado debido a la fuerte relación entre las variables académicas y la admisión.
Es importante evaluar más allá del Accuracy debido al desbalance de clases.

##Limitaciones
Ausencia de variables temporales.
Desbalance de la variable objetivo.
Posibles correlaciones entre SAT, ACT y GPA.
"""